services:
  mongodb:
    image: mongo:latest
    container_name: anmongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-api:
    build: .
    container_name: product-api
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://anmongodb:27017/productdb
      PORT: 3000
    depends_on:
      mongodb:
        condition: service_healthy